# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 10, 24, 27, 371323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='Due_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 10, 24, 27, 371323, tzinfo=utc)),
        ),
    ]
