# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180707_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 11, 10, 54, 792901, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='Due_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 11, 10, 54, 792901, tzinfo=utc)),
        ),
    ]
